# Generated by Django 4.0.2 on 2022-02-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=70)),
                ('model', models.CharField(default='', max_length=70)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
